
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Shader
{
	namespace Graphics
	{
		STRKEY Sample = "Sample.json";
	};
	namespace Compute
	{
	};
}