

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#include "PCH_UserContents.h"

#include "UserContentsInitializer.h"
#include <EngineBase/Engine/ComMgr.h>
#include "strKey_UserComponent.h"



#define CONSTRUCTOR_T(T) ComMgr::AddComConstructor<T>(strKey::com::##T)

namespace ehw
{
	using namespace ehw::define;
	void UserContentsInitializer::InitUserComponent()
	{
	}
}